dataset:
  batch_size: 64
  image_size: 64
  normalized: true
train:
  beta1: 0.5
  device: mps
  display: true
  image_size: 64
  in_channels: 1
  latent_space: 50
  learning_rate: 0.0002
  num_epochs: 200
