to_extract = "./data/raw/"
to_save = "./data/processed/"
TRAIN_MODELS = "./checkpoints/train_models/"
BEST_MODELS = "./checkpoints/best_models/"
TRAIN_YAML_PATH = "../"
TEST_IMAGE_PATH = "./outputs/test_images/"
TRAIN_IMAGE_PATH = "./outputs/train_images/"
TRAIN_GIF_PATH = "./outputs/train_gif/"
